server:
  port: 8083

spring:
  application:
    name: rides-microservice

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cab-aggregator-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:98479847}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

feign:
  client:
    passenger:
      url: ${PASSENGER_SERVER_URL:http://localhost:8081/api/passenger}
    driver:
      url: ${DRIVER_SERVER_URL:http://localhost:8082/api/driver}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off