server:
  port: 8083

spring:
  application:
    name: rides-microservice

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ride-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:98479847}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  cloud:
    openfeign:
      client:
        config:
          driver-microservice:
            url: ${DRIVER_SERVER_URL:http://localhost:8082/api/drivers}
          passenger-microservice:
            url: ${PASSENGER_SERVER_URL:http://localhost:8081/api/passengers}
      oauth2:
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/cab-agg}

  mail:
    username: ${MAIL_USERNAME:test.modsen.software.newsletter@gmail.com}
    password: ${MAIL_PASSWORD:uikz ilhl jnft fpoh}
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health, info, metrics, beans, caches, conditions, loggers, heapdump, threaddump, env'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true
  prometheus:
    metrics:
      export:
        enabled: true